name: video_picker
description: "video picker."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.riverolls.picker
        pluginClass: VideoPickerPlugin
      ios:
        pluginClass: VideoPickerPlugin
